### ISSUE TITLE
Ability to register a view / sql as a source node

### ISSUE THREAD

**Issue by vcknorket** [DataJunction/dj#1127]
Ability to register a view / sql as a source node will really help unlock and transition existing org artifacts to quickly onboard into DJ. Kind of equivalent of "brain-dump" of organizational semantic knowledge :) This is linked with https://github.com/DataJunction/dj/issues/1117

**Comment by agorajek** [comment]
Similarly to suggestion from #1117 we could add the following client method:

```
dj_client.create_source_from_query(
  query,      # (required) without the CREATE VIEW prefix, because we want to know the name
  view_name,  # (required)
  node_name,  # (optional)
  db-engine,  # (optional)
)
```

The above method would:
1. Runs the CRATE OR REPLACE VIEW view_name ... on the db-engine
2. Creates a new source node:
  - if `node_name` is not provided it can be inferred from the `view_name`
  - DJ will store the query as an attribute on the node, but it will not use it for anything other than showing it to the user [*]
  - DJ will create the source node based on the view name and will pull the schema from the the DB
  
[*] later on, we could extend this by adding the ability to edit, re-run the view creation and refreshing the node on demand.

**Comment by agorajek** [comment]
Yes, I will put this on my list for next week.

**Comment by ockhamlabs** [comment]
Curious what's the ETA for this?

**Comment by agorajek** [comment]
PR is ready... https://github.com/DataJunction/dj/pull/1153

**Comment by agorajek** [comment]
This work has been completed.

**Comment by vcknorket** [comment]
nice!
________________________________
