### ISSUE TITLE
Add the ability to always build down to source and ignore materialized tables

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#1158]
This should be added to the following endpoints:
* `GET /sql/<node>`
* `GET /sql/?metrics=...`
* `GET /sql/measures/v2?metrics=...`

In the `QueryBuilder` class, we can add a builder option like `use_materialized_table`, which can then be passed down into subsequent function calls like `build_ast` to not do the call to `get_table_for_node` for non-source nodes (which uses the materialized tables, if any).

**Comment by shangyian** [comment]
fyi @skastel in case you want to poke at this one

**Comment by samredai** [comment]
Since materializing tables is really a form of caching, I wonder if this should be implemented using cache directives where a request with `max-age=0` in the cache headers would then set `use_materialized_table=False` when building the query.

**Comment by skastel** [comment]
Using `max-age=0` to bypass the materialized table feels like a hidden feature, rather than intentional behavior to me. I would prefer an explicit flag to avoid confusion and keep future maintainers clear on the intended behavior for clients.

**Comment by shangyian** [comment]
Yeah, I also prefer that we add an explicit flag in the API call, because caching can refer to many things, including the actual caching of the generated queries themselves, which we also do in the DJ backend.
