### ISSUE TITLE
Use SQLite for the standard docker compose setup

### ISSUE THREAD

**Issue by samredai** [DataJunction/dj#225]
The *docker-compose.yml* that's used by default when running `docker compose up` should provide the simplest DJ setup possible to allow for easier demos and core development. So instead of including a postgres container and storing the metadata there, it should rely on the default behavior of DJ to use SQLite if no `INDEX` is set in the .env file.

A postgres backed DJ server should still be optionally available using a docker compose override.

*Start a DJ server that's backed by SQLite*
```
docker compose up
```

*Start a DJ server that's backed by Postgres*
```
docker compose -f docker-compose.yml -f docker-compose.postgres.yml up
```

**Comment by betodealmeida** [comment]
Implemented in #226.
