### ISSUE TITLE
Let's keep the autogenerated node IDs hidden.

### ISSUE THREAD

**Issue by agorajek** [DataJunction/dj#261]
Instead of using the internal node ids is our APIs, like `http://localhost:8000/metrics/2/`. 

Let's keep them hidden inside the system and use node names in our APIs, say `http://localhost:8000/metrics/num_comments/`.

And once we define the version ideas, then we can switch to `name/version` e.g. `http://localhost:8000/metrics/num_comments/0/`.

**Comment by samredai** [comment]
+1 on this! Also good call that we should think about versioning while we do this. 👍
