### ISSUE TITLE
Node Query Raw parts

### ISSUE THREAD

**Issue by CircArgs** [DataJunction/dj#273]
### Problem statement
This is a proposal to add an escape hatch syntax into the sql allowed in DJ node queries. There are many instances where queries could contain some database specific syntax that we either could parse under a very specific dialect or may never even be able to parse.

A trivial example would be a function we don't support but we can parse the query
```sql
SELECT myspecialfunc(x) FROM a
```
when we look to validate this we will not know the function to be able to infer the type. It would be possible to say something like ```Unknown function `...` specify the type of the expression `myspecialfunc(x)``` 
and then have the means to create nodes (API route) accept specified types. There are more advanced cases though where that would not be possible.

Take for example 

```sql
> SELECT map_zip_with(map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2) -> concat(v1, v2));
 {1:"ax",2:"by"}
```

from https://spark.apache.org/docs/latest/api/sql/index.html#map_zip_with

we have a combination of some specific functions as well as a lamba. I do not think any sqloxide dialects support this and so we would have to either expand our backends to maybe sqlglot which would introduce multiple extra layers of complexity from selecting default backend to the question of fallbacks... Besides, engines have not shown themselves to be too kind to following standards imo. Also, in the current state if new syntax comes out we automatically do not support it until we can completely parse it.

### Proposal

I think what could work is a dedicated syntax that just facilitates marking and escaping from parts of a query that can be typed expressions - essentially anywhere you could use a column or more complicated expression. 

Consider an Expression in sql which can ofc be many things (a single Column, Function, Case, a subquery, a primitive - int, str, bool, ...,) and will have a type that when creating a new node from sql we will need to know for validation. The Expression may contain other Expressions but most importantly it may contain Column(s). Columns are relevant because we would like to validate as part of a node creation that columns actually exist so that when the node enters the dag it doesn't invalidate potential parts of the dag that have it as a dependency (child DJ nodes).

To allow raw sql (unparsed) that still allows us type inference and column validation I propose something such as wrapping such expressions in a clear marking such as `${Expression : TYPE}` this signifies that this is a part of the sql that we need not worry about only that when we build the query we will dump `Expression` out and we can assume the type is `TYPE`. Further, should any sub-expressions exist within `Expression` that are parseable, they may be escaped with `{SubExpression}`

This is some pseudo metasyntax I think illustrates this further:
`${Expression({Expression})} | ${Expression}`

##### simple, parsable, unknown function
```sql
SELECT ${myspecialfunc({x})} FROM a
```

##### special function, constructs, lambda
```sql
> SELECT ${map_zip_with(map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2) -> concat(v1, v2)) : DICT};
 {1:"ax",2:"by"}
```

##### special function, expression embeds column from a TRANSFORM

```sql
SELECT ${apply_func({tfm_node.x}, (x) -> x+1) : INT} FROM tfm_node;
```

#### Implementation

I have already created a prototype of this method and the AST is designed with the compile, validate, build in mind. Namely, to facilitate this, I create a new AST Node `Raw`:
```python
Raw(
    name: str, # the name of the raw element automatically created
    expr_string: str, # the raw expression
    type: ColumnType, # the type defined in the raw expression syntax (: TYPE)
    expressions: List[ast.Expression], # a list of all sub-expressions escaped within the raw expression
    expression_hashes: List[int], # hashes used to recreate the original expression after `expressions` have passed through steps like build
)
```

parsing the query for this is fairly trivial and can be done with some regex.

Here is a small demo:

```python
from rich import print
from dj.sql.parsing.backends.sqloxide import parse

query = """
SELECT ${apply_func({tfm_node.x}, (x) -> x+1) : INT} FROM tfm_node
"""

print(parse(query))
print("#"*25)
print(str(parse(query)))
```

*OUTPUT:*
```python
Query(
    select=Select(
        from_=From(tables=[Table(name=Name(name='tfm_node', quote_style=''), namespace=None)], joins=[]),
        group_by=[],
        having=None,
        projection=[
            Raw(
                name='RAW_N3796958338935914076',
                expr_string='apply_func({EXPR_N7168611668097518469}, (x) -> x+1)',
                type=<ColumnType.INT: 'INT'>,
                expressions=[
                    Column(
                        name=Name(name='x', quote_style=''),
                        namespace=Namespace(names=[Name(name='tfm_node', quote_style='')])
                    )
                ],
                expression_hashes=['EXPR_N7168611668097518469']
            )
        ],
        where=None,
        limit=None,
        distinct=False,
        order_by=[]
    ),
    ctes=[]
)
#########################

#can perfectly recreate the original

SELECT  apply_func(tfm_node.x, (x) -> x+1) 
 FROM tfm_node
```

if the transform node were built and, for example could be materialized from a table `my_db.my_tbl`, since there is still a column we can trace at compile we would get:

```sql
SELECT  apply_func(my_db.my_tbl.x, (x) -> x+1) 
 FROM my_db.my_tbl
```

**Comment by betodealmeida** [comment]
> Take for example
> 
> ```sql
> > SELECT map_zip_with(map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2) -> concat(v1, v2));
>  {1:"ax",2:"by"}
> ```
> 
> from https://spark.apache.org/docs/latest/api/sql/index.html#map_zip_with
> 
> we have a combination of some specific functions as well as a lamba. I do not think any sqloxide dialects support this and so we would have to either expand our backends to maybe sqlglot which would introduce multiple extra layers of complexity from selecting default backend to the question of fallbacks... Besides, engines have not shown themselves to be too kind to following standards imo.

I'm a bit confused here. We shouldn't be parsing DB-specific SQL like this. We should only have to worry about parsing a single SQL dialect, "DJQL", which should be as close as possible to ANSI SQL, and is used to define nodes in a **DB-agnostic way**. Once we have parsed the SQL we can then translate it to DB-specific SQL.

In your example, we would define the node something like this:

```sql
SELECT map_zip_with(
  [map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2)],
  concat,
  [v1, v2]
);
```

Then in `sql/functions.py` we'd have (pseudocode):

```python
class MapZipWith(Function):
    @staticmethod
    def get_sqla_function(..., *, dialect: str) -> SqlaFunction:
        if dialect == "spark":
            return sqlalchemy.raw("map_zip_with(map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2) -> concat(v1, v2))")
        raise Exception(f"Function not supported in dialect {dialect}")
```

I don't remember if the current executor takes into consideration which dialects are supported for the functions when evaluating the best database to run a query (or the possible databases), but it should.

This way, we define nodes independently of the databases. It's the Java ("Write once, run anywhere") of SQL: people write the SQL query once, and they can run it in any database (assuming it supports all the functions and has all the tables).

With this approach, we can implement the `map_zip_with` function in different dialects. If you look at the defintion of `DateTrunc` (https://github.com/DataJunction/dj/blob/59c4e3669341feec96e2f549acb2706d2b18e1c2/dj/sql/functions.py#L166), we implement a single DJ function `date_trunc` than can be computed in many different databases, even ones that don't support the function natively.

**Comment by CircArgs** [comment]
@betodealmeida 

> In your example, we would define the node something like this:
> 
> ```sql
> SELECT map_zip_with(
>   [map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2)],
>   concat,
>   [v1, v2]
> );
> ```

My assumption about DJ overall is that there may be orgs attempting adoption with lots of users who either:

- are too pragmatic (lazy? 🥇) to convert a potentially large number of queries to an agnostic form
- do not have the knowledge (maybe I'm a poor example but I would fall into this bucket) to convert to an agnostic form

> Then in `sql/functions.py` we'd have (pseudocode):
> 
> ```python
> class MapZipWith(Function):
>     @staticmethod
>     def get_sqla_function(..., *, dialect: str) -> SqlaFunction:
>         if dialect == "spark":
>             return sqlalchemy.raw("map_zip_with(map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2) -> concat(v1, v2))")
>         raise Exception(f"Function not supported in dialect {dialect}")
> ```

My assumption about functions was that there are so many we would have to implement I don't feel like it would be practical would it? I thought we would do our best to cover the most common and still the user has to learn the DJ name of the one they are trying to use. So, if someone brings a query that uses a moderately obscure function we would have to implement it for their query to work or they would have to seek alternate avenues to write their query in an acceptable way?

**Comment by shangyian** [comment]
Ok, I think this issue below is related to this use case, but correct me if I'm wrong. 

Let's say that in my org someone has created a custom Spark function that they've deployed onto a given cluster. In that case, we wouldn't want to (nor would we be able to keep up with those changes) implement a `SqlaFunction` for that function. If we could instead have an escape hatch for that scenario, it would allow them to write that SQL without having to implement support for that function in DJ.

**Comment by agorajek** [comment]
Whoa, what a conversation... I wish I could give you both a winner trophy! But is there a way we can have both?

I get that requiring a user to provide a DJ SQL so we can parse everything and feel awesome is the best option, but is it always possible? We either parse the thing a user will give us or we fail and tell the user what we don't get. From there the user may say:
- I don't care about this system, cause it doesn't parse my little query. Se ya later.
- Or sees the little button below, that says "Need help parsing the query?"

If they press that button we could present them with some options say:
```
Hey there, we don't know what you meant by `my_little_udf(...)` but let's see if we can work it out:
(1) Pick this option if you are brave enough to give us a specification of your UDF, 
    this would be a fix for everyone later on, and your name would be on that contribution to our Metrics Platform.
    We will walk you through this so don't be shy.
(2) Pick this option if you'd like us to wrap the above UDFs in safety-on envelopes, so we can carry it inside the system w/o 
    knowing what it does. You can also point us to the referenced columns in order to tell us about your dependencies. 
    This option is less time-consuming and you will still be able to use DJ dependency graph. Just don't expect us to get
    too much praise for this. 
(3) This is the lazy-option, just click go and we will wrap your query in a flashing-red envelope. This is a way to learn of some
   other DJ features, but know that using this option will not give you all the benefits of this platform. Once you are ready
   to unlock the rest of the DJ awards, come back and help us resolve the parsing issues.
```

So... can we have it both ways? Or maybe even 3 ways?

**Comment by samredai** [comment]
I'm also on the side of including this as an escape hatch. @betodealmeida I agree with you that ideally we want all functions implemented and parseable by sqloxide and represented accurately in a DJ AST. For those reasons, I don't think this escape hatch should be highlighted front and center (maybe we don't include it anywhere in the docs).

All that being said, I think this escape hatch is an enormous aide when helping many many people migrate onto the system. When encountering some unrecognized syntax like those pesky scala-like arrow symbols in spark functions, it's nice that we can get that user rolling and then open an issue to get that function implemented. Huge plus that @CircArgs proposal allows for specifying the type of the output which keeps the column inference and node dependency logic all functioning properly. I think this explicit type signaling was something that was floated in a conversation about a very related feature, supporting custom user-defined functions.

**Comment by agorajek** [comment]
I am concerned that if we let users specify types and columns in a DJ SQL then they will "never" go the full way and add that to the system. Why would they? I think finding and instrumenting these "escape hatches" will be on the maintainers but I think I am willing to take that chance if that helps with on-boarding.

**Comment by betodealmeida** [comment]
I think there's two different topics here:

1. Allowing users to use DB-specific functions that DJ (still) doesn't know about.
2. Allowing users to use non-ANSI SQL (lambdas, eg).

For (1), @agorajek had suggested allowing functions to be passed by name when we don't recognize them. SQLAlchemy has support for arbitrary function names (it also passes them by name), but as we know the type inferer is then unable to know the schema of the node.

Ideally, though, we want to implement all the most common functions, because it brings so much more potential to the system. But you might ask:

> My assumption about functions was that there are so many we would have to implement I don't feel like it would be practical would it? 

Yes, and that's why DJ is the missing piece in the modern data stack — it's hard work. 🙂 It takes a lot foundational work to get it right. But I think that the current approach for defining function is almost as simple as it can be. We all could spend the day doing a marathon and implement the most common 100 functions.

That being said, I understand there are cases where people are in a hurry and want to add a function that is DB-specific, without having it implemented in DJ beforehand. When that happen, **I would strongly want for us to keep using ANSI SQL**, since it keeps the syntax simple and familiar, and gives us the flexibility of switching parsers, or using a JS parser in the web UI.

There are different ways we could implement this in ANSI SQL. Here we pass the function call as a string, the dialects it works on, and the return type:

```sql
SELECT DJ_UDF(
    "my_custom_function_in_spark(1, 2, col)",
    ["spark"],
    "ARRAY[INT]",
);
```

Or we could use comments for hints, and use the approach @agorajek suggested:

```sql
SELECT my_custom_function_in_spark(1, 2, col);  -- returns: ARRAY[INT]
```

My main concern is the same as @agorajek: as @CircArgs said, people are lazy (and they should be!), if they can write the SQL they know they will write the SQL they know. And the power of DJ comes from having transformations define in ways that can be computed in different engines.

**Comment by agorajek** [comment]
@betodealmeida thanks for separating the issues. I agree we have two here, even though for a user it may look like one.

> Allowing users to use DB-specific functions that DJ (still) doesn't know about.

Your comment and the `SELECT DJ_UDF(...` example gave me an idea. What if we allow a new CREATE UDF syntax to do exactly that, creating new UDFs that DJ does not know about yet, but right there from the DJ SQL prompt? I think this could work just like with any other "database". And in this case we could use @CircArgs's mechanism to add them to the parser on the fly (I think).

> Allowing users to use non-ANSI SQL (lambdas, eg).

This is the one that worries me more. On one side we cat just throw an error, and on the other we can say "No idea what your SQL does, but if you give us the output schema (cols + types) we can try to hold that for you as a node.". I think that finding any middle ground here will be tough and will feel icky.

**Comment by CircArgs** [comment]
@betodealmeida 

> ```sql
> SELECT DJ_UDF(
>     "my_custom_function_in_spark(1, 2, col)",
>     ["spark"],
>     "ARRAY[INT]",
> );
> ```

This looks like a nice compromise. It's basically the essence of my proposal but  introduces dialect. I think there would need to be a reference in this syntax that suggests there is a column used. + to your point it is ANSI

**Comment by agorajek** [comment]
@CircArgs if you allow the user to create the the UDF first with (no content) just the name and input and output types. Then you won't need to make any special column reference syntax, no?

**Comment by tobymao** [comment]
Why don't you just use SQLGlot to parse the SQL? I'm curious what the deficiencies of SQLGlot are that prevent you from going that route?

**Comment by CircArgs** [comment]
@agorajek 

I was thinking if we had

```sql
SELECT dbt.source.jaffle_shop.customers.id,
    first_name,
    last_name
FROM dbt.source.jaffle_shop.customers
```

after we compile the ast we know where each column came from (if compile succeeds) and so when we build we can correctly reference all columns to the appropriate source whether that be a subquery or a materialized table. In doing so, assuming `dbt.source.jaffle_shop.customers` is materialized in `jaffle_shop.customers` in the database, we would potentially build to (assuming that db was chosen)

```sql
SELECT jaffle_shop.customers.id,
    jaffle_shop.customers.first_name,
    jaffle_shop.customers.last_name
FROM jaffle_shop.customers
```

and to do that we need to know how that column is referenced. Assuming the column isn't namespaced in any way we would only really need to know (for this build resolution), to your point and even less (idt we need to know input types), the raw part and the output type.

```sql
SELECT DJ_UDF(
    "my_custom_function_in_spark(1, 2, col)", -- raw part
    ["spark"],
    "ARRAY[INT]", -- output type
);
```

perhaps an alternate signature would be

```
DJ_UDF(
name: str,
dialects: [str],
return_type: ColumnType,
*args: str|Column
)
```

where `*args` would be whatever goes into the function like `1, 2, col` above and we can parse it and we get our column as we would otherwise. If you have a lambda or something else you just pass it as a string and we don't care because we won't touch input types.

**Comment by samredai** [comment]
> Why don't you just use SQLGlot to parse the SQL? I'm curious what the deficiencies of SQLGlot are that prevent you from going that route?

We could use SQLGlot but I don't think it solves the problem being discussed in this thread. After parsing the SQL, we convert the AST to a DJ specific AST that carries metadata about the DAG of DJ nodes (sources, transforms, metrics, and dimensions). This includes type inference on the projection based on column metadata from upstream DJ nodes. Even if a custom function is parseable, we need to know two main things-the type of the return value and which columns from upstream nodes are used within the custom function.

**Comment by samredai** [comment]
> ```sql
> SELECT DJ_UDF(
>     "my_custom_function_in_spark(1, 2, col)",
>     ["spark"],
>     "ARRAY[INT]",
> );
> ```

I also like this syntax.

> perhaps an alternate signature would be
> ```
> DJ_UDF(
> name: str,
> dialects: [str],
> return_type: ColumnType,
> *args: str|Column
> )
> ```

I think what @betodealmeida was getting at is that with his proposed syntax it would still be ANSI SQL compliant. I don't know how interested people will be in the broader vision of having an ANSI SQL only system and the benefits that come with that. I suspect a few people will simply be bothered that they have to rewrite parts of their query (which they'd have to do with either proposed syntax). That being said I say we go with the ANSI SQL proposal that @betodealmeida offered, as @CircArgs said this is a nice compromise.

> @CircArgs if you allow the user to create the the UDF first with (no content) just the name and input and output types. Then you won't need to make any special column reference syntax, no?

@agorajek I really like this idea. I'm not trying to take over the world here but...should we maybe allow both? We can include an API for registering custom UDFs in which case after it's registered it's available to use without the additional arguments as you mentioned.
```sql
SELECT DJ_UDF(
    "my_pre_registered_custom_function_in_spark(1, 2, col)",
 );
```
However I think the best escape hatch to have in the moment when someone is migrating an existing query would be to define a temporary UDF within the query as in @CircArgs and @betodealmeida's proposals. If we really want to differentiate these, we could call it `DJ_TEMP_UDF`.
```sql
SELECT DJ_TEMP_UDF(
    "my_custom_function_in_spark(1, 2, col)",
    ["spark"],
    "ARRAY[INT]",
);
```

**Comment by tobymao** [comment]
> 

gotcha, thanks for the answer. sqlglot has type inference built in where you can override the return types of any function. 

https://github.com/tobymao/sqlglot/blob/main/sqlglot/optimizer/annotate_types.py#L35

**Comment by shangyian** [comment]
> (3) This is the lazy-option, just click go and we will wrap your query in a flashing-red envelope. 
    This is a way to learn of some other DJ features, but know that using this option will not give you 
    all the benefits of this platform. Once you are ready to unlock the rest of the DJ awards, come back 
    and help us resolve the parsing issues.

@agorajek this is an interesting one. I suspect there will be many circumstances where people are lazy (or lack the time to understand how to define a `DJ_UDF`), in which case they'll want to fall back to letting the system guess at the input and output types of the function. However, while guessing input is reasonable (we can just look at the types of the columns passed in, guessing output is harder. How would this third option you've described actually work? Would this essentially be a node that's `INVALID` until this UDF's definition is resolved?

**Comment by CircArgs** [comment]
@samredai can you elaborate how my adapted version of @betodealmeida would not meet the same standard?

**Comment by agorajek** [comment]
@shangyian yes, that 3rd option is what I consider an unparsed SQL. I think a bar for specifying the output schema in some cases may be lower than having someone fix all the SQL issues. We could still run some side functionalities of DJ (say materialization) if the user would tell us few things about their SQL rather than spend time fixing all parsing bugs. I don't consider it a flagship feature but rather an easy-onboarding one.

**Comment by agorajek** [comment]
@CircArgs and @samredai , maybe I missing something here, but I just don't see how adjusting a UDF signature inside a query makes things easier or cleaner fot the user than adding a CRATE UDF statement above that query and keeping the query in a "clean" state.

**Comment by samredai** [comment]
> @samredai can you elaborate how my adapted version of @betodealmeida would not meet the same standard?

@CircArgs I just meant that it wouldn't be parseable. The following is parseable by both sqloxide and sqlglot.
```sql
SELECT DJ_UDF(
    'my_custom_function_in_spark(1, 2, col)',
    ['spark'],
    'ARRAY[INT]'
) FROM tbl
```

> @CircArgs and @samredai , maybe I missing something here, but I just don't see how adjusting a UDF signature inside a query makes things easier or cleaner for the user than adding a CRATE UDF statement above that query and keeping the query in a "clean" state.

@agorajek I see, I didn't know you meant in the same query definition. Hmm, that also would not parse so we would have to do some pre-processing of the query, similar to @CircArgs's original proposal. Originally I thought you meant someone could separately globally register a function with a signature and then within any query they would only need to put the UDF call (and we lookup the engines and output types in the metadata store of global UDFs). That's something I also think would be a cool thing to eventually add so that users can register the UDF once through an API call and then it's understood everywhere.

**Comment by CircArgs** [comment]
Thanks @samredai. I think we agree now that something like the following is parseable

```sql
SELECT DJ_UDF('my_custom_function_in_spark', list('spark', 'trino'), 'LIST[INT]', 1, 2, col) FROM table
```

or

```sql
SELECT DJ_UDF('my_custom_function_in_spark', 'spark, trino', 'LIST[INT]', 1, 2, col) FROM table
```

**Comment by samredai** [comment]
@CircArgs agreed! Of the two options I like the second one. I know `list('spark', 'trino')` looks more legit but I like the simplicity of the second option where it's just a single function call with primitive arguments.

**Comment by agorajek** [comment]
> That's something I also think would be a cool thing to eventually add so that users can register the UDF once through an API call and then it's understood everywhere.

@samredai yes, that is exactly what I meant. Creating (using CREATE OR REPLACE) a UDF in the same session should mean that it is also available in the system.

@CircArgs are you expecting the users to use the above custom UDF syntax repeatably across their whole query if it happens that such UDF is called multiple times? Please tell me that I am missing something and they only need to do it once, even if they use that UDF many times in the query.

**Comment by CircArgs** [comment]
@agorajek 

>  Please tell me that I am missing something and they only need to do it once, even if they use that UDF many times in the query.

As it stands I don't have any better ideas than @betodealmeida suggestion to use something like this syntax to keep it standard sql and have it appear all over. I agree though, it's not nice. I defer to what others think would be the best route would be I think this has been a pretty productive thread for me.

To your earlier point:

> Hey there, we don't know what you meant by `my_little_udf(...)` but let's see if we can work it out:
...

we don't get column, line or any other context beyond the simple error message (e.g. expected ) found...) to what caused a parsing failure with sqloxide so I don't know how we would begin to say "we found this weird thing here what do you expect me to do with it?"

**Comment by samredai** [comment]
I think we've landed on a final two options:

**Option 1**
```sql
SELECT DJ_UDF('my_custom_function', 'spark, trino', 'LIST[INT]', 1, 2, col) FROM foo
```
This option is definitely parseable by sqloxide so we can start by immediately parsing the string as given. And then when converting the sqloxide input over to the DJ AST, we would look out for `DJ_UDF` functions that appear like this in the parse tree:
```py
{
    "projection": [
        {
            "UnnamedExpr": {
                "Function": {
                    "name": [{"value": "DJ_UDF", "quote_style": None}],
                    "args": [
                        {
                            "Unnamed": {
                                "Expr": {
                                    "Value": {
                                        "SingleQuotedString": "my_custom_function"
                                    }
                                }
                            }
                        },
                        {
                            "Unnamed": {
                                "Expr": {
                                    "Value": {"SingleQuotedString": "spark, trino"}
                                }
                            }
                        },
                        {
                            "Unnamed": {
                                "Expr": {"Value": {"SingleQuotedString": "LIST[INT]"}}
                            }
                        },
                        {"Unnamed": {"Expr": {"Value": {"Number": ("1", False)}}}},
                        {"Unnamed": {"Expr": {"Value": {"Number": ("2", False)}}}},
                        {
                            "Unnamed": {
                                "Expr": {
                                    "Identifier": {"value": "col", "quote_style": None}
                                }
                            }
                        },
                    ],
                    "over": None,
                    "distinct": False,
                }
            }
        }
    ]
}

```
The downside of this is if the function is used 20 times in the same SQL query, the user would have to define it as `DJ_UDF('my_custom_function', 'spark, trino', 'LIST[INT]', 1, 2, col)` 20 times.

**Option 2**
```sql
CREATE FUNCTION my_custom_function(int, int, column) ENGINES 'spark,trino' RETURNS 'LIST[INT]';
SELECT my_custom_function(1, 2, col) FROM foo
```
This option is nice in that the user only has to define the engines and return type once at the top, and then if they use the function 20 times in their code, they can simply call the function with the args, `my_custom_function(1, 2, col)`. The downside here is that this entire query string is not directly parseable by SQL so we would have to do some pre-processing to interpret the `CREATE FUNCTION` call and then strip it out before sending the rest to sqloxide. I don't know how much this overhead is worth it to prevent having to specify the engines and return type every time.

---
However I want to bring it all the way back to the original thing we're looking for here which is an escape hatch to use when someone brings an unknown/un-parseable function, worst case being a custom UDF where we do not know the return types. Take the example in @CircArgs description for this issue.
```sql
SELECT map_zip_with(map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2) -> concat(v1, v2));
 {1:"ax",2:"by"}
```
Even if we provide a mechanism for someone to rewrite this function, we have to go ahead an implement the function that will take `DJ_UDF("map_zip_with", "spark", "MAP", "map(1, 'a', 2, 'b')", "map(1, 'x', 2, 'y')", "(k, v1, v2)", "concat(v1, v2)")` and produce the original query (including the `->`). It doesn't feel like an escape hatch if we have to open, merge, and deploy a PR to utilize it.

I keep finding myself coming back to this proposal in the description of this issue:

> **special function, expression embeds column from a TRANSFORM**
> ```sql
> SELECT ${apply_func({tfm_node.x}, (x) -> x+1) : INT} FROM tfm_node;
> ```

It requires no PRs to use, keeps both node/column dependencies working properly, and most important of all, it produces the original string exactly as defined. If we can squeeze an array of supported engines into this, I think I'd be completely sold, keeping in mind that this is not a syntax we'd advertise or recommend be used. As we march towards our long term goal of implementing engine specific functions (and finding a way to support user-defined functions that include the lambda expression arrow `->`), in success we will never (or very rarely) have to use this feature and can probably remove it.

**Comment by shangyian** [comment]
@samredai For both option 1 and option 2 in your list above, my understanding is that no PRs are required. The UDF can get defined in that session and then be made available for use immediately after. I think option 2 would generally be what users prefer, since you can declare it once and then reuse. Also, the syntax for option 2 is significantly closer to what most users are familiar with when declaring custom functions. I think we should aim to support option 2 in the long run, but it can be punted on for now.

Ultimately I think users should be able to just specify the function name, the input args and types, the output args and types, and have that be enough for the purposes of parsing. They can also implement the function if needed, but if the actual implementation already defined in a custom cluster for an engine, that's unnecessary.

**Comment by samredai** [comment]
@shangyian with Option 2 are you imagining we just include those pesky lamba functions by treating the entire element as a string? Using the example from the spark docs:
```sql
SELECT map_zip_with(map(1, 'a', 2, 'b'), map(1, 'x', 2, 'y'), (k, v1, v2) -> concat(v1, v2))
```
With Option 2 maybe we could write something like this?
```sql
CREATE FUNCTION map_zip_with(str, str, str) ENGINES 'spark' RETURNS 'MAP';
SELECT map_zip_with("map(1, 'a', 2, 'b')", "map(1, 'x', 2, 'y')", "(k, v1, v2) -> concat(v1, v2)")
```
Another one from the spark docs is:
```sql
SELECT aggregate(some_array_of_arrays_column, 0, (acc, x) -> acc + x, acc -> acc * 10)
```
which Option 2 would mean
```sql
CREATE FUNCTION aggregate(str, str, str, str) ENGINES 'spark' RETURNS 'INT';
SELECT aggregate("an_array_of_arrays_column[0]", "0", "(acc, x) -> acc + x", "acc -> acc * 10")
```
Maybe that's the solution but it still breaks column/node dependencies. `an_array_of_arrays_column` above actually comes from the upstream node which we'll need to detect and add that relationship in the metadata. Should we go with Option 2 but also include the curly brace column identifying syntax?
```sql
CREATE FUNCTION aggregate(str, str, str, str) ENGINES 'spark' RETURNS 'INT';
SELECT aggregate("{an_array_of_arrays_column}[0]", "0", "(acc, x) -> acc + x", "acc -> acc * 10")
```

**Comment by agorajek** [comment]
Had a short discussion with @samredai this morning. We agreed that this topic of trying to do something nice for the users, when we really can't parse their UDFs should not be derailing us from the short term goals. But we should have come up with some quick temporary solution that would give us good stage for addressing this issue in the future and here is what we got.

1. If sqloxide can parse the UDF and DJ does not know about it, then we can keep doing the pass-through. 

2. If sqloxide breaks on parsing a UDF then we can wrap the whole UDF call in a single `RAW()` function, specify the return type (either as 2nd argument, or using Postgres casting syntax), and optionally reference the columns. This way we are not putting too much burden on the user (or ourselves) while preserving the original code so we can address it and fix it later. See below:

Breaking input: `... SELECT aggregate(array(1, 2, col3), 0, (acc, x) -> acc + x, acc -> acc * 10) FROM node_one ...`

Working input: 
 - 2nd arg for return type: 
    `... SELECT RAW("aggregate(array(1, 2, {col3}), 0, (acc, x) -> acc + x, acc -> acc * 10)", "INT") FROM node_one ...`
 - Postgres syntax for return type: 
    `... SELECT RAW("aggregate(array(1, 2, {col3}), 0, (acc, x) -> acc + x, acc -> acc * 10)")::INT FROM node_one ...`

3. There is still the open question of what do we do if the outer SQL parsing breaks, but that's a separate issue.

**Comment by samredai** [comment]
Big +1 here. I think this is an important area of the source code that I wouldn't want to rush to a solution on (or add a ton of code for an intermediate solution that has to be unwinded later). I think the `RAW` as a very simple blunt escape hatch that gives us some breathing room to accumulate a good number of examples of un-parseable non-ANSI bits so that we can come up with a solid long term solution.
