### ISSUE TITLE
Create a route that allows posting diff-based materialization availability states for nodes

### ISSUE THREAD

**Issue by samredai** [DataJunction/dj#274]
A few recent discussions have let to the idea of having an endpoint where external services can post the availability of materialized tables for a given node. This will allow materialization metadata to get updated asynchronously and then discovered during the building of SQL queries. The availability state should also include information about which partitions have been materialized and should be diff-based, meaning that a newly posted availability state is always merged with the existing availability state of the node.

```py
class AvailabilityState:
  id: int
  node_name: str
  catalog: str
  schema: str
  table: str
  valid_through_ts: int
  max_partition: str
  min_partition: str
```

**Comment by agorajek** [comment]
Min and max partitions will likely need to be `{str: str}` dicts.

**Comment by agorajek** [comment]
Never mind my previous comment. We concluded that list of strings will be ok for now.
