### ISSUE TITLE
Add a unique identifer for source node

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#294]
We should have some way of identifying the columns that serve as a unique identifier for a source node.

**Comment by samredai** [comment]
+1 on this. Is it something that's useful to enable for all nodes not just source nodes?

**Comment by shangyian** [comment]
Yeah, agreed, it would be useful on all nodes!

**Comment by shangyian** [comment]
Now supported with https://github.com/DataJunction/dj/pull/394
