### ISSUE TITLE
Metrics should have a user-friendly name

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#300]
The current `Node.name` serves as a unique identifier / system identifier, and `Node.description` works as a longer description of the metric. However, in addition to description and a system identifier, metrics should also have a short, user-friendly name. 

Not sure about naming, perhaps `friendly_name`?

**Comment by samredai** [comment]
+1, maybe `descriptive_name`?

**Comment by shangyian** [comment]
I like `display_name`!

**Comment by agorajek** [comment]
+1 on `display_name`. But to distinguish it from `name` and `description` perhaps it should:
- be unique, just like `name`
- be a limited length, unlike `description`

Not a strong opinion. Just trying to make the use of it match its purpose.

**Comment by samredai** [comment]
@agorajek I agree with the limited length requirement but I don't know if it should be unique. It's not used in any logic in the code so it's essentially a free form "human-readable" text for UI purposes only. I don't even think it should be versioned. We don't have to worry about it breaking any links or bookmarks either since those will utilize the `name` or `id` values which can't be changed.

**Comment by agorajek** [comment]
I agree it will be hard to maintain sensible uniqueness if the field is completely free form. I think we are gonna be OK, as long as we send the (unique by definition) metric name always next to a display name and use the metric name as an additional piece of info, or the only one, if `display_name` is not present. Wondering if @betodealmeida has any opinion?

**Comment by shangyian** [comment]
I think `display_name` should be version controlled. I've definitely seen instances where users are confused after something gets renamed, so it would be better to have a record that we can point users towards if needed. 

I think uniqueness can be nice in the sense that we can force people to really think about duplicates. However, it's also possible for some metrics to be named the same but under different categories...

**Comment by agorajek** [comment]
+1 on versioning `display_name`.

**Comment by shangyian** [comment]
I made it unique here: https://github.com/DataJunction/dj/pull/311 But on second thought perhaps enforcing it is a bad idea, especially if we allow for some form of metric categorization.

**Comment by betodealmeida** [comment]
`display_name` sounds good!

@shangyian do you think it would be confusing for users if the display name is not unique? We'd have to also show the name (which might be too technical, since it uses dot notation for directories, ie, foo.bar) or the description (which might be too verbose).

**Comment by shangyian** [comment]
@betodealmeida I agree that it could be confusing for users. I think the issue is that some users will want to create metrics with the same name (and it would actually make sense for them to do so), but these metrics might live under different categories, so essentially the categories serve as differentiators. However, given that we don't currently have categorization for metrics, makes sense to keep `display_name` unique for now, and we can relax the unique constraint when / if we add categories.

**Comment by shangyian** [comment]
https://github.com/DataJunction/dj/pull/311
