### ISSUE TITLE
A better way for attaching columns to dimensions for new nodes (through the API*)

### ISSUE THREAD

**Issue by samredai** [DataJunction/dj#308]
I noticed that attaching a dimension to a node as you're creating it is sort of awkward. When creating nodes, the user doesn't think about columns at all since columns and column types are inferred from the parsed SQL query. For example, here's an example request for creating a transform node.

_POST "/nodes/"_
```json
{
   "description":"Revenue data filtered to large payments only",
   "query":"SELECT payment_id, payment_amount, customer_id, account_type FROM revenue_source LEFT JOIN payment_type on payment_type = payment_type.id WHERE payment_amount > 1000000",
   "mode":"published",
   "name":"large_revenue_payments_only",
   "type":"transform"
}
```
_response_
```json
{
   "id":21,
   "name":"large_revenue_payments_only",
   "type":"transform",
   "current_version":"1",
   "created_at":"2023-02-07T18:58:04.385384+00:00",
   "current":{
      "id":21,
      "name":"large_revenue_payments_only",
      "version":"1",
      "node_id":21,
      "description":"Revenue data filtered to large payments only",
      "updated_at":"2023-02-07T18:58:04.386891+00:00",
      "type":"transform",
      "query":"SELECT payment_id, payment_amount, customer_id, account_type FROM revenue_source LEFT JOIN payment_type on payment_type = payment_type.id WHERE payment_amount > 1000000",
      "availability":null,
      "columns":[
         {
            "name":"payment_id",
            "type":"INT"
         },
         {
            "name":"payment_amount",
            "type":"FLOAT"
         },
         {
            "name":"customer_id",
            "type":"INT"
         },
         {
            "name":"account_type",
            "type":"STR"
         }
      ],
      "tables":[
         
      ]
   }
}
```
As you can see in the response, the column names were inferred from the parsed SQL and the upstream types were determined by the node dependencies implicit in the SQL query. What I find "awkward" here is how for the user to connect the `account_type` column to an `account_types` dimension node that already exists in the system, they'd have to essentially add an override of the columns section that would have been otherwise automatically inferred. We could tell them to perform a call to `PATCH "/nodes/large_revenue_payments_only"` afterwards and that would work, but it's sort of the same problem and seems like we're providing a blunt instrument for something that will be done very very frequently and could benefit from dedicated functional logic with contextual error messages for bad requests.

**Comment by CircArgs** [comment]
Would it be reasonable to do this discovery via compile? I think the way the information saturates the AST we would have all we need to determine fairly easily if columns originate from the same place unadulterated (by which I guess could mean a few things such as no transformations were applied to the column directly or even more loosely that the type is the same as the original)

**Comment by agorajek** [comment]
Let's assume there is a single namespace of dimension names (preferably singular, e.g. `account_type`). 

Labeling of columns (in any nodes) as these dimensions could happen in two ways:

1. Automagical, as @CircArgs noted we could analyze "the source path" of every column in the newly created node and if: 
     a) the column comes from a node where it is already marked as some dimension X
     b) the column is not transformed in any way, that includes maintaining the type
 then we mark this column as dimension X. 
   Extra bonus points: if we "know" that there is a filter (where clause or join based) on that column between the "source" and the current node, we can mark this dimension as "partial". Note that this analysis will be unnecessary if the "source" column is already tagged as "partial".

2. Manual, through an API like @samredai mentioned we let the users say something like: `POST "/nodes/{node}/{column}/dim/{dimension}"`. We can do some basic sanity check right there as raise a red flag if the data types don't match or "something". 

Now... let's say someone wasn't sure if a column is a dimension but still told DJ to mark it so. By the next morning our dear Reflection service, that could do useful things when users sleep, could go into the nodes, find the user-slapped dimension attributes on columns and do some useful analysis. And if it finds some ridiculous results it should flag the columns. Maybe not Invalid node right away but do something to help folks make good choices... Did we talk about the "Users with Most Invalid Nodes" as the DJ landing page yet?

**Comment by samredai** [comment]
> Did we talk about the "Users with Most Invalid Nodes" as the DJ landing page yet?

![ted-laugh](https://user-images.githubusercontent.com/43911210/217562296-ad82fd61-646d-4e34-8b45-82ed85d3d165.gif)

**Comment by CircArgs** [comment]
does #314 allow this to be closed?
