### ISSUE TITLE
Enable type inference for arbitrarily complex maps

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#339]
The current setup disallows arbitrarily complex maps and doesn't do type inference when a map's contents is queried via the subscription operator `[]` (it instead raises a `Failed to parse Expression` exception).

Suppose we have a source node `foo` with a column `measures_map` of type `MAP[STR, FLOAT]`. This following query should be parseable and the type of `measure_name` be inferred from the upstream type of `measures_map` to be `FLOAT`:
```
SELECT measures_map["measures_name"] AS measure_name FROM foo
```

**Comment by CircArgs** [comment]
Our AST is something of a hybrid between sqlglot's and sqloxide's. pdb'ing into the failure for your example, I see the sqloxide parse tree looks like `{'MapAccess': {'column': {'Identifier': {'value': 'measures_map', 'quote_style': None}}, 'keys': [{'Value': {'SingleQuotedString': 'measures_name'}}]}}`.

Based on that, I can see this going a couple of ways

- a. some optional attributes on the existing `Column` ast node to account for this
- A new node (inheriting from existing `Column`?) that is special:
    - b. special in that is has the custom attribute for this
    - c. special in that it is exactly a map access and then we need one for all other kinds 

imo b, a, c would be my order of preference and a, b are very close. c seems gross.

To start to implement this, there's the sort of orchestrator function for all expressions that forks to specialized parsers https://github.com/DataJunction/dj/blob/8c99b979fb7fc3e1140ed4292966253f0f2b1d27/dj/sql/parsing/backends/sqloxide.py#L101

then you might consider extending the column one https://github.com/DataJunction/dj/blob/8c99b979fb7fc3e1140ed4292966253f0f2b1d27/dj/sql/parsing/backends/sqloxide.py#L187 or implementing a new specialized one.

**Comment by shangyian** [comment]
@CircArgs I added a new `MapSubscript` object that inherits from `Expression` and handles the parsing of the `MapAccess` parse tree in https://github.com/DataJunction/dj/pull/340. Do you think it should inherit from `Column` instead though?

**Comment by CircArgs** [comment]
@shangyian 

> @CircArgs I added a new `MapSubscript` object that inherits from `Expression` and handles the parsing of the `MapAccess` parse tree in #340. Do you think it should inherit from `Column` instead though?

I don't think so since you have the column attribute on it. Maybe it should inherit from `Operator`?
