### ISSUE TITLE
Add column annotations to identify primary keys on dimension nodes

### ISSUE THREAD

**Issue by samredai** [DataJunction/dj#388]
As we think through the more complex join patterns, it's becoming crucial that we know the primary key for a given dimension node. Similar to #386, we should also have column annotations on dimension nodes that annotate which columns make up the primary key for the dimension node to inform joins.

**Comment by shangyian** [comment]
https://github.com/DataJunction/dj/pull/394 adds a `primary_key` column attribute (to the set of default system-level attributes) so this is now solved!
