### ISSUE TITLE
Support `CROSS JOIN` and `UNNEST`

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#393]
We don't currently allow for `CROSS JOIN`s. This is relatively easy to support by adding a `JoinKind` check and creating a different join type that accepts just a table to join with. However, `CROSS JOIN` is often used with `UNNEST` (to extract rows from a `MAP` or `ARRAY`), but `UNNEST` gets parsed by sqloxide as a table name rather than a function.

An example:
```python
from dj.sql.parsing.backends.sqloxide import parse
parsed = parse_sql(
    "SELECT student, score FROM tests CROSS JOIN UNNEST(scores) AS t (score)",
    dialect="ansi"
)

# Drill down to the UNNEST:
parsed[0]['Query']['body']['Select']['from'][0]['joins'][0]['relation']
```
yields
```python
{
  "Table": {
    "name": [
      {
        "value": "UNNEST",
        "quote_style": "None"
      }
    ],
    "alias": {
      "name": {
        "value": "t",
        "quote_style": "None"
      },
      "columns": [
        {
          "value": "score",
          "quote_style": "None"
        }
      ]
    },
    "args": [
      {
        "Unnamed": {
          "Expr": {
            "Identifier": {
              "value": "scores",
              "quote_style": "None"
            }
          }
        }
      }
    ],
    "with_hints": []
  }
}
```

We could probably add a special case that checks to see if the table after cross joins contains a name of `UNNEST`, but this feels hacky. @CircArgs curious to hear your take on how to support this.

**Comment by CircArgs** [comment]
@shangyian actually I think sqloxide's output makes sense and is deliberate. I think this is a failure of the current ast I didn't account for table valued functions. I'm imagining a few routes but I feel as though the most pragmatic thing to do is to look for tables with args, break out the function and add an attribute to `Function` that flags it as a TVH. What do you think of that?

**Comment by CircArgs** [comment]
added a couple things for this to https://github.com/DataJunction/dj/issues/393

**Comment by shangyian** [comment]
@CircArgs I'm circling back to this one again, and yep, agreed that that's the right approach! Going to take a stab at this unless you think the antlr grammar will change how this gets parsed (I assume not).

**Comment by CircArgs** [comment]
@samredai @shangyian I'm sketching stuff for the new parser with some changes to the AST. You can peek and lmk what you think https://github.com/CircArgs/dj/blob/custom-parser/Untitled.ipynb (ignore my habit of dumping everything in nondescript notebooks, I am, after all, a lowly data scientist) will also add you as collaborators on my form of you would like to mess with it there as well lmk

**Comment by samredai** [comment]
@CircArgs awesome, I'll take a look! Just as a sanity check we can start testing the queries we have and update the grammar for anything that's missing (unless it's something we don't plan to support). Other than that it looks like it's just a matter of us filling in these visit functions.

**Comment by CircArgs** [comment]
@samredai great idea! What queries do you have in mind? Tpcds?

**Comment by samredai** [comment]
@CircArgs tpcds plus the ones we've discussed recently (lateral view explode, lambda functions, and cross join unnest). That should definitely get us close to or all the way to complete coverage of everything we expect to encounter. Not sure if @shangyian has come across anything else recently...

**Comment by shangyian** [comment]
Yeah, I think starting with tpcds makes sense. I'll continue stress testing + fixing things on my end and will bring up whatever I find.

**Comment by shangyian** [comment]
I've been playing around with the antlr grammar more and this is great!

In fact, here's one where the original sqloxide parser fails to parse correctly:
```
SELECT
      name,
      scores,
    FROM some_table where 
      scores['1'] = '111' and scores['2'] = '222'
```
It yields this, which is missing the subscript `'2'` in the second `scores` comparison:
```
[
...
               "selection":{
                  "BinaryOp":{
                     "left":{
                        "BinaryOp":{
                           "left":{
                              "BinaryOp":{
                                 "left":{
                                    "MapAccess":{
                                       "column":{
                                          "Identifier":{
                                             "value":"scores",
                                             "quote_style":"None"
                                          }
                                       },
                                       "keys":[
                                          {
                                             "Value":{
                                                "SingleQuotedString":"1"
                                             }
                                          }
                                       ]
                                    }
                                 },
                                 "op":"Eq",
                                 "right":{
                                    "Value":{
                                       "SingleQuotedString":"111"
                                    }
                                 }
                              }
                           },
                           "op":"And",
                           "right":{
                              "Identifier":{
                                 "value":"scores",
                                 "quote_style":"None"
                              }
                           }
                        }
                     },
                     "op":"Eq",
                     "right":{
                        "Value":{
                           "SingleQuotedString":"222"
                        }
                     }
                  }
               },
...
]
```

But I tested it with the antlr grammar and the parsing is done right.
