### ISSUE TITLE
Node created without namespace isn't assigned one

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#488]
If a node is created without a namespace (i.e., the name is just `repair_orders`), we should assign `default` as the namespace and save that to the node name (i.e., the node's name should be `default.repair_orders`). This fits with the downstream logic, which assumes that the node's namespace is always part of the name.

**Comment by samredai** [comment]
@shangyian to avoid confusion I think we should maintain this shorthand when retrieving the nodes as well, do you agree? In other words, if someone requests `repair_orders` then we should automatically find and return `default.repair_orders`. 

Something that I'm worried about though is the situation where someone writes some reasonable logic that requests a node and has follow-up logic that (very reasonably) includes an expectation that the node returned has the same name as the node requested.
```py
name = "repair_orders"
node = dj.node(name)
assert node.name == "repair_orders"  # raises an error since "repair_orders" != "default.repair_orders"
```
Where these thoughts are leading me is that maybe we should abandon all of this default namespace logic and just make a user-defined namespace an absolute requirement by the server. We already allow `DEFAULT_NAMESPACE` to be configurable in clients, maybe we should avoid any special treatment server side and leave it to the clients to make sure a namespace is always included in requests. Am I crazy?

**Comment by shangyian** [comment]
@samredai I agree, let's just make the namespace an absolute requirement so that it's super clear what the API is doing.

**Comment by CircArgs** [comment]
@shangyian so the implication is just raising if there is no namespace right?

**Comment by shangyian** [comment]
@CircArgs yep, it just raises if there's no namespace so nothing is implicit.
