### ISSUE TITLE
Type inference fails for struct select

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#491]
We don't do type inference correctly for struct selections. 

For example, the following query, with `counts` being of type `struct<a string, b bigint>`, fails type inference:
```
SELECT SUM(counts.b) FROM source
```

An example unit test for the failure:

```
def test_struct_select_type_inference(client_with_examples: TestClient):
    """
    Testing struct select type inference
    """

    client_with_examples.post("/nodes/source/",
        json={
            "columns": [
                {"name": "id", "type": "int"},
                {"name": "painter", "type": "string"},
                {
                    "name": "counts",
                    "type": "struct<a string, b bigint>",
                },
            ],
            "description": "Murals",
            "mode": "published",
            "name": "basic.murals2",
            "catalog": "public",
            "schema_": "basic",
            "table": "murals2",
        },
    )

    response = client_with_examples.post("/nodes/metric/",
        json={
            "query": "SELECT SUM(counts.b) FROM basic.murals2",
            "description": "Mural Counts",
            "mode": "published",
            "name": "basic.mural_count",
        },
    )
```

One issue is that `sbp.DereferenceContext` cannot always be interpreted as a `<table>.<column>` and can sometimes be `<column>.<field>`.

**Comment by CircArgs** [comment]
@shangyian taking a look at this. here is a dummy minimal example:

```python
query = parse("SELECT SUM(counts.b) FROM (select cast(_ as struct<a string, b bigint>) as counts) dummy")
```

compiling `query` we get the expected `DJError(code=<ErrorCode.INVALID_COLUMN: 206>, message='Column`counts.b` does not exist on any valid table.', debug=None, context='')` on the exception in the compilation context.

You mention an issue while visiting `sbp.DereferenceContext` but I wonder if we can address this in the ast by maybe in https://github.com/DataJunction/dj/blob/95a2c033074fbb6503d37c58e06068d9054d7e28/dj/sql/parsing/ast.py#L907 making the check more sophisticated when using the namespace columns. 

https://github.com/DataJunction/dj/blob/95a2c033074fbb6503d37c58e06068d9054d7e28/dj/sql/parsing/ast.py#L945-L953

**Comment by shangyian** [comment]
@CircArgs good point, I think something like this should work:

```
                # For struct types we can additionally check if there's a column that matches
                # the search column's namespace and if there's a nested field that matches the
                # search column's name
                if isinstance(col.type, StructType):
                    column_namespace = ".".join([name.name for name in column.namespace])
                    if column_namespace == current_col_name:
                        for field in col.type.fields:
                            if field.name.name == column.name:
                                column.add_table(self)
                                column.add_expression(col)
                                column.add_type(field.type)
```

Although I wasn't able to reproduce it with just compile, still had to go with the less minimal example with compile + build.

**Comment by samredai** [comment]
@shangyian maybe try this example? I couldn't get it to work with the cast either but I was able to reproduce using `named_struct`.
```py
from dj.errors import DJException
from dj.sql.parsing.ast import CompileContext
from dj.sql.parsing.backends.antlr4 import parse

err = DJException()
ctx = CompileContext(
    session=session,
    exception=err,
)
query = parse("SELECT SUM(counts.b) FROM (select named_struct('a', '1', 'b', 2) as counts) dummy")
query.compile(ctx)
print(err.errors)
```

**Comment by shangyian** [comment]
Ok I can confirm that this snippet added to add_ref_column works:
```python
                # For struct types we can additionally check if there's a column that matches
                # the search column's namespace and if there's a nested field that matches the
                # search column's name
                if isinstance(col.type, StructType):
                    column_namespace = ".".join([name.name for name in column.namespace])
                    if column_namespace == current_col_name:
                        for field in col.type.fields:
                            if field.name.name == column.name.name:
                                column.add_table(self)
                                column.add_expression(col)
                                column.add_type(field.type)
```

**Comment by shangyian** [comment]
@samredai Hmm, I get an error with that example saying that `named_struct` hasn't been implemented yet 😕

**Comment by shangyian** [comment]
Oh yeah, another weird thing is that the API always responds with:
```
Unable to infer type for some columns on node
```

It might be nice if it actually surfaced the specific DJParseException like say `Not all the same type in CASE! Found ...`.

**Comment by samredai** [comment]
> @samredai Hmm, I get an error with that example saying that `named_struct` hasn't been implemented yet 😕

Woah...😅 

<img width="980" alt="Screenshot 2023-05-04 at 7 57 54 PM" src="https://user-images.githubusercontent.com/43911210/236354060-cede4d77-5ca3-4304-9f74-a884f07febde.png">

**Comment by samredai** [comment]
> Oh yeah, another weird thing is that the API always responds with:
> 
> ```
> Unable to infer type for some columns on node
> ```
> 
> It might be nice if it actually surfaced the specific DJParseException like say `Not all the same type in CASE! Found ...`.

+1, the API should be returning the array of errors from the error context whenever possible.

**Comment by shangyian** [comment]
Added another commit that should surface the errors in the response (it's a bit confusing because we have two types of errors, type inference specific errors and compile-time errors): https://github.com/DataJunction/dj/pull/495/commits/30317e66fc87ae05be3b6357b4eba86f712173f7
