### ISSUE TITLE
Filter validation

### ISSUE THREAD

**Issue by CircArgs** [DataJunction/dj#519]
Currently we validate that dimensions exist when a call is made from the api, but we do not extract the columns from filters to validate that they are from shared dimensions.

This is where the ordinary groupby dimensions are validated for example:
https://github.com/DataJunction/dj/blob/9424702275d90cfea1e6528dcfe2eac7459e6125/dj/construction/build.py#L487-L493

**Comment by shangyian** [comment]
Good catch!
