### ISSUE TITLE
Support lambda functions in node query

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#543]
We should be able to use lambda functions when writing node queries. An example would be:

```
SELECT aggregate(array(1, 2, 3), 0, (acc, next) -> acc + next)
> 6
```

**Comment by CircArgs** [comment]
@shangyian we can already parse lambdas with the new parser I believe. 
<img width="668" alt="Screenshot 2023-05-31 at 11 50 54 AM" src="https://github.com/DataJunction/dj/assets/35903677/2939af77-c51a-4758-8a7c-702d4e16bdfb">

**Comment by shangyian** [comment]
@CircArgs So the parsing works, but then the type inference fails, which then causes node creation to fail. I think we need a custom compile function for `Lambda` that adds the types to `acc` and `next`, and this would have to implemented for each custom function (i.e., `aggregate` would be different from `array_sort` etc).
