### ISSUE TITLE
Cleanup Node creation/restoring.

### ISSUE THREAD

**Issue by agorajek** [DataJunction/dj#674]
And also adjust the Node [de]activate to delete/restore.

Nodes:
 - delete() - deactivates the node (we need to hide it in the UI)
 - restore() - brings it back to the world
 - create() - works fine if the node never existed or if it is deactivated, so people don't need to worry about the state of deleted nodes
 
Namespaces: --> moved to another issue

If that's ok then we need:
 - an "active" flag at the Node level, I thin we have it already
 - and a similar flag at the Namespace level.

**Comment by samredai** [comment]
This all makes sense to me. For some context, the way we determine the active/inactive state for a node is using the [deactivated_at](https://github.com/DataJunction/dj/blob/main/datajunction-clients/python/datajunction/nodes.py#L73) timestamp attribute. So a node is considered active if that value is null. We should use a similar pattern for namespaces to keep it consistent.

**Comment by agorajek** [comment]
@samredai agreed. Ideally I would like to rename everything from "[de]activated" to "deleted|restored" but I wonder if I should touch that attribute at this point.

**Comment by samredai** [comment]
Oh I wasn't suggesting to change the attribute, I was just saying we should use the same kind of timestamp attribute for activating/deactivating a namespace, as opposed to using something like a boolean.
