### ISSUE TITLE
proposal: landing page image

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#692]
![image](https://github.com/DataJunction/dj/assets/9524628/65c913a6-9586-449b-8741-0ba888b8724b)

I just spent some time in Figma and came out with the above. What do we think about having this be the landing page image under "introduction" in the docs? @samredai @agorajek @CircArgs @betodealmeida 

Let me know if you want something different on there! (and @CircArgs if you have a vectorized logo for Headjack I can put it on)

**Comment by samredai** [comment]
Yes!
