### ISSUE TITLE
Hard delete doesn't propagate to downstreams beyond first layer

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#725]
Hard deleting a node invalidates only the first layer of downstream nodes, but it doesn't propagate down to all subsequent layers of downstreams. For example, when a source node is hard deleted, it will invalidate a transform that depends on it, but the metrics that depend on the transform remain valid. They should all be invalid.

**Comment by samredai** [comment]
Thanks @shangyian, good catch! It looks like it's just relying on [get_downstream_nodes](https://github.com/DataJunction/dj/blob/main/datajunction-server/datajunction_server/api/helpers.py#L245). I wonder if that function isn't including the metrics in your example.
